version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: sumkam_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./backend:/usr/src/app
    ports:
      - '4000:4000'
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/sumkam_db
      PORT: 4000
      MPESA_BASE_URL: https://sandbox.safaricom.co.ke
      BACKEND_URL: http://localhost:4000
    depends_on: [db]
volumes:
  db_data:
